[project]
name = "canis-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "layoutparser[detectron2]>=0.3.4",
    "mcp>=1.9.0",
    "pytesseract>=0.3.13",
    "requests>=2.32.3",
]
